language: d

d:
  - dmd

before_script:
  - |
    cd public
    for repo in */ ; do
      git clone https://github.com/soupply/${repo////}.git ../gen/$repo
      cd ../gen/$repo
      git rm -rf .
      cd ../../public
    done
    cd ..

script:
  - VERSION=1.0.$(( TRAVIS_BUILD_NUMBER - 188 ))
  - echo $VERSION > version.txt
  - dub run -- --diff

after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - DESC="Automatically committed from https://github.com/sel-project/soupply/commit/${TRAVIS_COMMIT}"
  - git config --global user.email ${EMAIL}
  - git config --global user.name ${USER}
  - |
    cd gen
    for repo in */ ; do
      cd $repo
      if [ ! -f ".nopush" ] ; then
        git add --all .
        git commit -m "${MESSAGE}" -m "${DESC}"
        git tag -a "v${VERSION}" -m "${MESSAGE}"
        git push -u --follow-tags "https://${TOKEN}@github.com/soupply/${repo////}.git" master
      fi
      cd ..
    done

notifications:
  - email: false