language: d

d:
 - dmd-2.073.2

notifications:
 - email: false

script:
 - cd gen && echo $(( TRAVIS_BUILD_NUMBER - 88 )) > version.txt
 - rdmd all.d
 - cd .. && rdmd --build-only push.d

after_success:
 - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
 - DESC="Automatically committed from https://github.com/sel-project/sel-utils/commit/${TRAVIS_COMMIT}"
 - echo "${MESSAGE}" > message.txt
 - echo "${DESC}" > desc.txt
 - git config --global user.email ${EMAIL}
 - git config --global user.name ${USER}
 - git clone git://${REPO_GP} gp
 - rm -r gp/protocol
 - rm -r gp/api
 - cp -r -f pages/. gp/protocol
 - mkdir gp/api
 - cp -r -f src/json/sul/. gp/api/json
 - cp -r -f src/js/sul/. gp/api/js
 - cd gp
 - git add --all .
 - git commit -m "${MESSAGE}" -m "${DESC}"
 - git push "https://${TOKEN}@${REPO_GP}" master
 - cd ..
 - ./push php true src eyJleGNsdWRlIjpbInN1bFwvdXRpbHNcL0Fib3V0LnBocCJdLCJpbmNsdWRlIjpbXX0=
 - ./push java true src/main/java eyJleGNsdWRlIjpbInN1bFwvdXRpbHNcL0Fib3V0LmphdmEiXSwiaW5jbHVkZSI6W119
 - ./push d true src eyJleGNsdWRlIjpbInN1bFwvdXRpbHNcL2Fib3V0LmQiXSwiaW5jbHVkZSI6W119
 - ./push csharp true src eyJleGNsdWRlIjpbInN1bFwvVXRpbHNcL0Fib3V0LmNzIiwiUHJvcGVydGllc1wvQXNzZW1ibHlJbmZvLmNzIl0sImluY2x1ZGUiOlsic2VsLXV0aWxzLmNzcHJvaiIsIlByb3BlcnRpZXNcL0Fzc2VtYmx5SW5mby5jcyJdfQ==
