language: d

d:
  - dmd

before_script:
  - cd public
  - for repo in */ ; do git clone https://github.com/soupply/${repo////}.git ../gen/$repo ; done
  - cd ..

script:
  - SOUPPLY_VERSION=1.1.$(( TRAVIS_BUILD_NUMBER - 184 ))
  - dub run

after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - DESC="Automatically committed from https://github.com/sel-project/soupply/commit/${TRAVIS_COMMIT}"
  - git config --global user.email ${EMAIL}
  - git config --global user.name ${USER}
  - |
    cd gen
    for repo in */ ; do
      cd $repo
      git add --all .
      git commit -m "${MESSAGE}" -m "${DESC}"
      git tag -a "v${SOUPPLY_VERSION}" -m "${MESSAGE}"
      git push -u --follow-tags "https://${TOKEN}@github.com/soupply/${repo////}.git" master
      cd ..
    done

notifications:
  - email: false